name: kfc_seller
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.19.0
  crypto: ^3.0.3
  mongo_dart: ^0.9.3
  image_picker: ^1.0.7
  cloudinary_public: ^0.23.1
  http_auth: ^1.0.2
  http: ^0.13.6
  webview_flutter: ^4.2.2
  url_launcher: ^6.2.4
  mailer: ^6.4.1
  random_string: ^2.3.1
  pinput: ^5.0.1
  lottie: ^3.0.0  # Cho animations
  shimmer: ^3.0.0 # Cho loading effects
  cached_network_image: ^3.3.0 # Cho image caching
  location: ^5.0.3
  geocoding: ^2.1.1
  map_launcher: ^3.0.1
  permission_handler: ^11.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/image-home/
    - assets/images/banner/
    - assets/images/banking/

